/* Auto-generated by cbindgen */

#ifndef FINALYTICS_FFI_H
#define FINALYTICS_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Portfolio {
  uint8_t _dummy;
} Portfolio;

typedef struct Portfolio *PortfolioHandle;

typedef struct Screener {
  uint8_t _dummy;
} Screener;

typedef struct Screener *ScreenerHandle;

typedef struct Ticker {
  uint8_t _dummy;
} Ticker;

typedef struct Ticker *TickerHandle;

typedef struct Tickers {
  uint8_t _dummy;
} Tickers;

typedef struct Tickers *TickersHandle;

void finalytics_free_string(char *ptr);

PortfolioHandle finalytics_portfolio_new(const char *ticker_symbols,
                                         const char *benchmark_symbol,
                                         const char *start_date,
                                         const char *end_date,
                                         const char *interval,
                                         double confidence_level,
                                         double risk_free_rate,
                                         const char *objective_function,
                                         const char *asset_constraints,
                                         const char *categorical_constraints,
                                         const char *weights,
                                         const char *tickers_data,
                                         const char *benchmark_data);

void finalytics_portfolio_free(PortfolioHandle handle);

int finalytics_portfolio_optimization_results(PortfolioHandle handle, char **output);

int finalytics_portfolio_optimization_chart(PortfolioHandle handle,
                                            unsigned int height,
                                            unsigned int width,
                                            char **output);

int finalytics_portfolio_performance_chart(PortfolioHandle handle,
                                           unsigned int height,
                                           unsigned int width,
                                           char **output);

int finalytics_portfolio_asset_returns_chart(PortfolioHandle handle,
                                             unsigned int height,
                                             unsigned int width,
                                             char **output);

int finalytics_portfolio_returns_matrix(PortfolioHandle handle,
                                        unsigned int height,
                                        unsigned int width,
                                        char **output);

int finalytics_portfolio_report(PortfolioHandle handle, const char *report_type, char **output);

ScreenerHandle finalytics_screener_new(const char *quote_type,
                                       const char *filters,
                                       const char *sort_field,
                                       int sort_descending,
                                       unsigned int offset,
                                       unsigned int size);

void finalytics_screener_free(ScreenerHandle handle);

int finalytics_screener_symbols(ScreenerHandle handle, char **output);

int finalytics_screener_overview(ScreenerHandle handle, char **output);

int finalytics_screener_metrics(ScreenerHandle handle, char **output);

int finalytics_screener_display(ScreenerHandle handle, char **output);

TickerHandle finalytics_ticker_new(const char *symbol,
                                   const char *start_date,
                                   const char *end_date,
                                   const char *interval,
                                   const char *benchmark_symbol,
                                   double confidence_level,
                                   double risk_free_rate,
                                   const char *ticker_data,
                                   const char *benchmark_data);

void finalytics_ticker_free(TickerHandle handle);

int finalytics_ticker_get_quote(TickerHandle handle, char **output);

int finalytics_ticker_get_summary_stats(TickerHandle handle, char **output);

int finalytics_ticker_get_price_history(TickerHandle handle, char **output);

int finalytics_ticker_get_options_chain(TickerHandle handle, char **output);

int finalytics_ticker_get_news(TickerHandle handle, char **output);

int finalytics_ticker_get_income_statement(TickerHandle handle,
                                           const char *frequency,
                                           int formatted,
                                           char **output);

int finalytics_ticker_get_balance_sheet(TickerHandle handle,
                                        const char *frequency,
                                        int formatted,
                                        char **output);

int finalytics_ticker_get_cashflow_statement(TickerHandle handle,
                                             const char *frequency,
                                             int formatted,
                                             char **output);

int finalytics_ticker_get_financial_ratios(TickerHandle handle,
                                           const char *frequency,
                                           char **output);

int finalytics_ticker_volatility_surface(TickerHandle handle, char **output);

int finalytics_ticker_performance_stats(TickerHandle handle, char **output);

int finalytics_ticker_performance_chart(TickerHandle handle,
                                        unsigned int height,
                                        unsigned int width,
                                        char **output);

int finalytics_ticker_candlestick_chart(TickerHandle handle,
                                        unsigned int height,
                                        unsigned int width,
                                        char **output);

int finalytics_ticker_options_chart(TickerHandle handle,
                                    const char *chart_type,
                                    unsigned int height,
                                    unsigned int width,
                                    char **output);

int finalytics_ticker_news_sentiment_chart(TickerHandle handle,
                                           unsigned int height,
                                           unsigned int width,
                                           char **output);

int finalytics_ticker_report(TickerHandle handle, const char *report_type, char **output);

TickersHandle finalytics_tickers_new(const char *symbols,
                                     const char *start_date,
                                     const char *end_date,
                                     const char *interval,
                                     const char *benchmark_symbol,
                                     double confidence_level,
                                     double risk_free_rate,
                                     const char *tickers_data,
                                     const char *benchmark_data);

void finalytics_tickers_free(TickersHandle handle);

int finalytics_tickers_get_summary_stats(TickersHandle handle, char **output);

int finalytics_tickers_get_price_history(TickersHandle handle, char **output);

int finalytics_tickers_get_options_chain(TickersHandle handle, char **output);

int finalytics_tickers_get_news(TickersHandle handle, char **output);

int finalytics_tickers_get_income_statement(TickersHandle handle,
                                            const char *frequency,
                                            int formatted,
                                            char **output);

int finalytics_tickers_get_balance_sheet(TickersHandle handle,
                                         const char *frequency,
                                         int formatted,
                                         char **output);

int finalytics_tickers_get_cashflow_statement(TickersHandle handle,
                                              const char *frequency,
                                              int formatted,
                                              char **output);

int finalytics_tickers_get_financial_ratios(TickersHandle handle,
                                            const char *frequency,
                                            char **output);

int finalytics_tickers_returns(TickersHandle handle, char **output);

int finalytics_tickers_performance_stats(TickersHandle handle, char **output);

int finalytics_tickers_returns_chart(TickersHandle handle,
                                     unsigned int height,
                                     unsigned int width,
                                     char **output);

int finalytics_tickers_returns_matrix(TickersHandle handle,
                                      unsigned int height,
                                      unsigned int width,
                                      char **output);

int finalytics_tickers_report(TickersHandle handle, const char *report_type, char **output);

TickerHandle finalytics_tickers_get_ticker(TickersHandle handle, const char *symbol);

PortfolioHandle finalytics_tickers_optimize(TickersHandle handle,
                                            const char *objective_function,
                                            const char *asset_constraints,
                                            const char *categorical_constraints,
                                            const char *weights);

#endif  /* FINALYTICS_FFI_H */
